language: php

php:
  - 5.5
  - 5.6
  - 7.0

env:
  - COMPOSER_OPTS=""
  - COMPOSER_OPTS="--prefer-lowest"

before_install:
  - composer self-update

install:
  - composer install --no-interaction

script:
  - vendor/bin/phpunit --coverage-text

